# Generated by Django 4.2.1 on 2023-05-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_film', models.CharField(blank=True, max_length=50)),
                ('producer', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(blank=True)),
                ('rating', models.IntegerField(default=0)),
                ('awards', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='films', to='films.category')),
            ],
        ),
    ]
