# Generated by Django 4.2.1 on 2023-05-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_raiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
