# Generated by Django 4.2.1 on 2023-06-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_autor_alter_book_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('fr', 'French')], max_length=2),
        ),
    ]
